// Code generated by hertz generator.

package template

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	template "github.com/cloudwego/hz/client/biz/model/cloudwego/hertz/template"
)

// BizMethod2 .
// @router /life/client1 [POST]
func BizMethod2(ctx context.Context, c *app.RequestContext) {
	var err error
	var req template.Req
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(template.Resp)

	c.JSON(200, resp)
}

// BizMethod3 .
// @router /life/client2 [POST]
func BizMethod3(ctx context.Context, c *app.RequestContext) {
	var err error
	var req template.Req
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(template.Resp)

	c.JSON(200, resp)
}

// BizMethod4 .
// @router /life/client3 [POST]
func BizMethod4(ctx context.Context, c *app.RequestContext) {
	var err error
	var req template.Req
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(template.Resp)

	c.JSON(200, resp)
}
