// Code generated by hertz generator.

package Template

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _lifeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bizmethod2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bizmethod3Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bizmethod4Mw() []app.HandlerFunc {
	// your code...
	return nil
}
